### ISSUE TITLE
windbg fails to install on Windows Server 2012

### ISSUE THREAD

**Issue by staticshock** [mwrock/Chocolatey-Packages#20]
My theory as to what's going on is that the same policy that blocks IE on Windows Server from making requests to non-whitelisted URLs is blocking Chocolatey from downloading the package. This was in my log:

> [0A8C:032C][2014-10-01T09:48:04]: Error 0x80070002: Failed to send request to URL: http://download.microsoft.com/download/B/0/C/B0C80BA3-8AD6-4958-810B-6882485230B5/standalonesdk/allers/SDK Debuggers-x86_en-us.msi

I went to that URL directly in IE and saw that it was, indeed, being blocked, even though I can go to http://download.microsoft.com. In IE, the error was:

> Your current security settings do not allow this file to be downloaded.

Tested w/Chocolatey v0.9.8.27.

**Comment by icnocop** [comment]
Hi.

I believe this is an issue in the windbg bootstrapper caused by running the installer using `$env:temp` which expands to a short (8.3) path.

In order to resolve this issue, I had to expand `$env:TEMP` to it's full name and use that to execute the installer.

See a more detailed explanation here:
https://github.com/patrickmaurer/chocolatey-packages/issues/3#issuecomment-1166704268
